# Initial Logistic Regression

## Import packages

In [1]:
import numpy as np
import pandas as pd
import mord
from sklearn import linear_model, metrics, preprocessing

## Read data

In [2]:
path = '../../data/cleaned'
training = pd.read_csv(path + '/training_cleaned_v1.csv')
testing = pd.read_csv(path + '/testing_cleaned_v1.csv')

In [3]:
print (training.isnull().sum())
training.columns

id                           0
amount_tsh                   0
year_recorded                0
month_recorded               0
day_recorded                 0
gps_height                   0
basin                        0
region                       0
population                   0
public_meeting            3334
permit                    3056
age                      20709
extraction_type              0
extraction_type_group        0
extraction_type_class        0
management                   0
management_group_new         0
payment                      0
quantity_group               0
quality_group_new            0
source                       0
source_type                  0
source_class                 0
waterpoint_type_new          0
status_group                 0
status_group_new             0
dtype: int64


Index(['id', 'amount_tsh', 'year_recorded', 'month_recorded', 'day_recorded',
       'gps_height', 'basin', 'region', 'population', 'public_meeting',
       'permit', 'age', 'extraction_type', 'extraction_type_group',
       'extraction_type_class', 'management', 'management_group_new',
       'payment', 'quantity_group', 'quality_group_new', 'source',
       'source_type', 'source_class', 'waterpoint_type_new', 'status_group',
       'status_group_new'],
      dtype='object')

## Ordinal Logistic Regression

In [4]:
le = preprocessing.LabelEncoder()

In [5]:
# encode region
le.fit(training['region'])
training['region_new'] = le.transform(training['region'])
training[['region','region_new']] # can label if not NA

region  region_new
0             Iringa           3
1               Mara           9
2            Manyara           8
3             Mtwara          12
4             Kagera           4
5              Tanga          20
6          Shinyanga          17
7          Shinyanga          17
8             Tabora          19
9             Kagera           4
10             Pwani          14
11            Ruvuma          16
12         Shinyanga          17
13       Kilimanjaro           6
14         Shinyanga          17
15             Rukwa          15
16            Iringa           3
17            Iringa           3
18            Mwanza          13
19            Iringa           3
20            Iringa           3
21         Shinyanga          17
22            Iringa           3
23       Kilimanjaro           6
24            Kigoma           5
25       Kilimanjaro           6
26             Lindi           7
27            Kagera           4
28       Kilimanjaro           6
29       Kilimanjaro           6
...              ...         ...
59370         Kigoma           5
59371      Shinyanga          17
59372         Tabora          19
59373          Rukwa          15
59374      Shinyanga          17
59375          Tanga          20
59376        Singida          18
59377         Tabora          19
59378         Iringa           3
59379         Kagera           4
59380         Iringa           3
59381          Tanga          20
59382    Kilimanjaro           6
59383          Lindi           7
59384         Kagera           4
59385           Mara           9
59386          Rukwa          15
59387  Dar es Salaam           1
59388         Kigoma           5
59389          Rukwa          15
59390          Rukwa          15
59391    Kilimanjaro           6
59392          Mbeya          10
59393         Tabora          19
59394       Morogoro          11
59395    Kilimanjaro           6
59396         Iringa           3
59397          Mbeya          10
59398         Dodoma           2
59399       Morogoro          11

[59400 rows x 2 columns]

In [6]:
# extraction_type_class
le.fit(training['extraction_type_class'])
training['extraction_type_class_new'] = le.transform(training['extraction_type_class'])
training[['extraction_type_class','extraction_type_class_new']]

extraction_type_class  extraction_type_class_new
0                   gravity                          0
1                   gravity                          0
2                   gravity                          0
3               submersible                          5
4                   gravity                          0
5               submersible                          5
6                  handpump                          1
7                  handpump                          1
8                  handpump                          1
9                  handpump                          1
10              submersible                          5
11                 handpump                          1
12                 handpump                          1
13                  gravity                          0
14                 handpump                          1
15                 handpump                          1
16                  gravity                          0
17                  gravity                          0
18                    other                          3
19                  gravity                          0
20                  gravity                          0
21                 handpump                          1
22                  gravity                          0
23                  gravity                          0
24                  gravity                          0
25                  gravity                          0
26                 handpump                          1
27                 handpump                          1
28                  gravity                          0
29                  gravity                          0
...                     ...                        ...
59370                 other                          3
59371              handpump                          1
59372                 other                          3
59373              handpump                          1
59374              handpump                          1
59375               gravity                          0
59376                 other                          3
59377               gravity                          0
59378               gravity                          0
59379               gravity                          0
59380               gravity                          0
59381               gravity                          0
59382               gravity                          0
59383              handpump                          1
59384               gravity                          0
59385              handpump                          1
59386              handpump                          1
59387           submersible                          5
59388               gravity                          0
59389              handpump                          1
59390              handpump                          1
59391               gravity                          0
59392               gravity                          0
59393               gravity                          0
59394           submersible                          5
59395               gravity                          0
59396               gravity                          0
59397              handpump                          1
59398              handpump                          1
59399              handpump                          1

[59400 rows x 2 columns]

In [7]:
le.fit(training['public_meeting'])
training['pm_encoded'] = le.transform(training['public_meeting'])
training[['public_meeting','pm_encoded']] # cannot label if NA

ValueError: y contains new labels: [nan nan nan ... nan nan nan]

In [8]:
sum(training['status_group_new'] == 1)

22824

In [9]:
# just try
X, y = training.loc[:,('amount_tsh', 'gps_height', 'region_new', 'population','extraction_type_class_new')], training['status_group_new']

In [14]:
reg0 = linear_model.LogisticRegression(
    solver='lbfgs',
    multi_class='multinomial')
reg0.fit(X, y)
print (reg0.predict(X))
print('Mean Absolute Error of LogisticSE %s' %
      metrics.mean_absolute_error(reg0.predict(X), y))
print (sum(reg0.predict(X)==1))

[3 3 3 ... 1 1 3]
Mean Absolute Error of LogisticSE 0.7626094276094276
15995


In [10]:
reg1 = mord.LogisticAT(alpha=1.)
reg1.fit(X, y)
print (reg1.predict(X))
print('Mean Absolute Error of LogisticSE %s' %
      metrics.mean_absolute_error(reg1.predict(X), y))
print (sum(reg1.predict(X)==1))

[3 3 3 ... 3 3 3]
Mean Absolute Error of LogisticSE 0.7808417508417509
8487


In [11]:
reg2 = mord.LogisticIT(alpha=1.)
reg2.fit(X, y)
print (reg2.predict(X))
print('Mean Absolute Error of LogisticSE %s' %
      metrics.mean_absolute_error(reg2.predict(X), y))
print (sum(reg2.predict(X)==1))

[3 3 3 ... 3 3 3]
Mean Absolute Error of LogisticSE 0.7463804713804714
12174


In [12]:
reg3 = mord.LogisticSE(alpha=1.)
reg3.fit(X, y)
print (reg3.predict(X))
print('Mean Absolute Error of LogisticSE %s' %
      metrics.mean_absolute_error(reg3.predict(X), y))
print (sum(reg3.predict(X)==1))

[3 2 2 ... 2 2 2]
Mean Absolute Error of LogisticSE 0.9088888888888889
0


In [15]:
# use reg2 on test set:

In [16]:
# encode region
le.fit(testing['region'])
testing['region_new'] = le.transform(testing['region'])
testing[['region','region_new']] # can label if not NA

region  region_new
0            Manyara           8
1             Arusha           0
2            Singida          18
3              Lindi           7
4             Ruvuma          16
5             Arusha           0
6             Iringa           3
7             Mtwara          12
8             Mtwara          12
9        Kilimanjaro           6
10       Kilimanjaro           6
11           Manyara           8
12            Tabora          19
13            Mwanza          13
14            Iringa           3
15            Ruvuma          16
16             Pwani          14
17             Tanga          20
18         Shinyanga          17
19            Mtwara          12
20     Dar es Salaam           1
21            Iringa           3
22            Kigoma           5
23           Singida          18
24         Shinyanga          17
25            Iringa           3
26            Ruvuma          16
27            Dodoma           2
28         Shinyanga          17
29           Manyara           8
...              ...         ...
14820          Lindi           7
14821    Kilimanjaro           6
14822         Mtwara          12
14823          Mbeya          10
14824       Morogoro          11
14825         Mtwara          12
14826      Shinyanga          17
14827         Mwanza          13
14828          Pwani          14
14829         Ruvuma          16
14830    Kilimanjaro           6
14831         Mwanza          13
14832         Arusha           0
14833         Iringa           3
14834         Dodoma           2
14835      Shinyanga          17
14836          Pwani          14
14837         Kigoma           5
14838         Iringa           3
14839          Tanga          20
14840         Ruvuma          16
14841      Shinyanga          17
14842         Kigoma           5
14843         Kigoma           5
14844      Shinyanga          17
14845          Pwani          14
14846          Tanga          20
14847        Singida          18
14848         Ruvuma          16
14849         Ruvuma          16

[14850 rows x 2 columns]

In [17]:
# extraction_type_class
le.fit(testing['extraction_type_class'])
testing['extraction_type_class_new'] = le.transform(testing['extraction_type_class'])

In [18]:
X_test = testing.loc[:,('amount_tsh', 'gps_height', 'region_new', 'population','extraction_type_class_new')]
prediction_test = reg2.predict(X_test)
print (prediction_test)
print (sum(prediction_test==1))

[3 3 3 ... 3 3 3]
3170


In [19]:
# Let's get a submission!
testing['prediction_label'] = prediction_test
testing['status_group'] = np.where((testing['prediction_label'] == 1), 
                                                 'non functional', np.where((testing['prediction_label'] == 3), 'functional', 'functional needs repair'))
out = testing[['id', 'status_group']]

In [20]:
path_out = '../../data/submissions'
out.to_csv(path_out + '/out_v1.csv', index = False)

# To Do

## 1. Update data cleaning to make all categorical to numeric

## 2. Deal with NAs (mord does not seem like it), maybe fill? Then try mord more carefully and figure out what is going on for each method

## 3. stepwise try to figure out

## 4. try out other models

## 5. Maybe Write a CV function